### ISSUE TITLE
File information 

### ISSUE THREAD

**Issue by abhik1368** [fimrie/DeLinker#1]
C[C@H](NC(=O)NCCc1ccccn1)c1ccc(F)cc1Cl C[C@H](NC(=O)N[*:1])[*:2] Fc1ccc([*:2])c(Cl)c1.c1ccc(CC[*:1])nc1 **6.06 2.77**

What are these two values in the train files and how do we compute it ?

**Comment by fimrie** [comment]
Hello. These values represent the distance (in Angstrom) and angle (in Radians) between the unlinked substructures (in your example represented by Fc1ccc([:2])c(Cl)c1.c1ccc(CC[*:1])nc1).
