### ISSUE TITLE
Why not consider using Tensorflow 2.0?

### ISSUE THREAD

**Issue by zhouhao-learning** [fimrie/DeLinker#3]
Hello, it is nice to see your work, but I see that your code is implemented based on Tensorflow 1.10. For now, 　 Tensorflow 2.0 is more popular, and it is relatively easy for code developers Debugging, why don’t you consider using Tensorflow 2.0?

**Comment by fimrie** [comment]
Thank you for the suggestion. We will take this into account for any future updates/releases.

**Comment by MKCarter** [comment]
Turns out you need to use the tf_upgrade_v2 script that Tensorflow2 comes with to convert all of the python scripts to enable this to work with Tensorflow2 :) - Happy to push the changes to a new branch if you think it would be helpful.
